name: CI

on:
  push:
    branches:
      - main

# env:
#   DENO_DIR: .deno_cache

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      # - name: Cache Deno dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: ${{ env.DENO_DIR }}
      #     key: ${{ secrets.CACHE_VERSION }}-${{ hashFiles('deno.lock') }}

      - name: Run tests
        id: run_tests
        run: |
          deno task test > test_output.txt

      - name: Run benchmarks
        id: run_benchmarks
        run: |
          deno task bench > benchmark_output.txt

      - name: Tag as 'latest' and push tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -f latest  # Force update the 'latest' tag to the latest commit
          git push origin latest --force  # Force push the 'latest' tag
          echo "### Latest Tag" >> $GITHUB_STEP_SUMMARY
          echo "The tag has been updated to 'latest'." >> $GITHUB_STEP_SUMMARY

      - name: Send POST request
        run: |
          curl -X POST "https://coa-utils.deno.dev/${{ secrets.URL_PATH_KEY }}/slack/coa_utils" -d '{}'
