name: Continuous Integration

on:
  push:
    branches:
      - main

env:
  DENO_DIR: .deno_cache

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Cache Deno dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ secrets.CACHE_VERSION }}-${{ hashFiles('deno.lock') }}

      - name: Run tests
        id: run_tests
        run: |
          TEST_OUTPUT=$(deno task test)
          echo "TEST_OUTPUT=$TEST_OUTPUT" >> $GITHUB_ENV

      - name: Run benchmarks
        id: run_benchmarks
        run: |
          BENCHMARK_OUTPUT=$(deno task bench)
          echo "BENCHMARK_OUTPUT=$BENCHMARK_OUTPUT" >> $GITHUB_ENV

      - name: Add Job Summary
        run: |
          echo "## Test and Benchmark Summary" >> $GITHUB_STEP_SUMMARY
          echo "Ran tests and benchmarks for the project. Here are the results:" >> $GITHUB_STEP_SUMMARY
          
          echo "### Test Output" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "${{ env.TEST_OUTPUT }}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

          echo "### Benchmark Output" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "${{ env.BENCHMARK_OUTPUT }}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      - name: Increment version and push tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch --tags
          latest_tag=$(
