name: Continuous Integration

on:
  push:
    branches:
      - main

env:
  DENO_DIR: .deno_cache

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Cache Deno dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ secrets.CACHE_VERSION }}-${{ hashFiles('deno.lock') }}
      - name: Run tests
        id: run_tests
        run: |
          deno test --allow-write --allow-read --allow-env > test_output.txt
    
      - name: Run benchmarks
        id: run_benchmarks
        run: |
          deno bench --allow-env --allow-read --allow-write utils/utils_bench.ts > benchmark_output.txt
    
      - name: Add Job Summary
        run: |
          echo "## Test and Benchmark Summary" >> $GITHUB_STEP_SUMMARY
          echo "Ran tests and benchmarks for the project. Here are the results:" >> $GITHUB_STEP_SUMMARY
  
          # Adding test output to summary
          echo "### Test Output" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cat test_output.txt >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
  
          # Adding benchmark output to summary
          echo "### Benchmark Output" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cat benchmark_output.txt >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
      - name: Increment version and push tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          IFS='.' read -r -a version_parts <<< "$latest_tag"
          major="${version_parts[0]}"
          minor="${version_parts[1]}"
          new_minor=$((minor + 1))
          new_version="$major.$new_minor"
          git tag "$new_version"
          git push origin "$new_version"
