name: CI

on:
  push:
    branches:
      - main

env:
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  SLACK_DEFAULT_CHANNEL_ID: ${{ secrets.SLACK_DEFAULT_CHANNEL_ID }}
  DENO_DIR: .deno_cache
  tests: "passed"
  benchmarks: "passed"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Cache Deno dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ secrets.CACHE_VERSION }}-${{ hashFiles('deno.lock') }}

      - name: Run tests
        id: run_tests
        run: deno task test || echo "tests=failed" >> $GITHUB_ENV

      - name: Run benchmarks
        id: run_benchmarks
        run: deno task bench || echo "benchmarks=failed" >> $GITHUB_ENV

      - name: Increment version and push tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          IFS='.' read -r -a version_parts <<< "$latest_tag"
          major="${version_parts[0]}"
          minor="${version_parts[1]}"
          new_minor=$((minor + 1))
          new_version="$major.$new_minor"
          echo "new_version=$new_version" >> $GITHUB_ENV
          git tag "$new_version"
          git push origin "$new_version"

      - name: Send POST request to Slack
        run: |
          curl -X POST "https://coa-utils.deno.dev/${{ secrets.URL_PATH_KEY }}/slack/coa_utils" \
          -H "Content-Type: application/json" \
          -d "{
              \"tests\": \"${{ env.tests }}\",
              \"benchmarks\": \"${{ env.benchmarks }}\",
              \"latest\": \"${{ env.new_version }}\"
          }"
