name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run tests
        run: deno test --allow-write --allow-read --allow-env

      - name: Run benchmarks
        run: deno bench --allow-env --allow-read --allow-write utils/utils_bench.ts

      - name: Increment version and push tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          version=$(git describe --tags --abbrev=0)
          IFS='.' read -r -a version_parts <<< "$version"
          major="${version_parts[0]}"
          minor="${version_parts[1]}"
          new_minor=$((minor + 1))
          new_version="$major.$new_minor"
          git tag "$new_version"
          git push origin "$new_version"
